// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Repository;

#nullable disable

namespace ToDoList.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220815180428_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoList.Core.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Added");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DuetoDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DueTo");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2022, 8, 15, 21, 4, 28, 596, DateTimeKind.Local).AddTicks(2795),
                            Content = "falan filanda zımpırtı yapılacak",
                            DuetoDateTime = new DateTime(2022, 8, 25, 21, 4, 28, 596, DateTimeKind.Local).AddTicks(2811),
                            IsDone = false,
                            Title = "Yapılacak 2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2022, 8, 15, 21, 4, 28, 596, DateTimeKind.Local).AddTicks(2822),
                            Content = "falan filanda zımpırtı yapılacak",
                            DuetoDateTime = new DateTime(2022, 9, 4, 21, 4, 28, 596, DateTimeKind.Local).AddTicks(2823),
                            IsDone = false,
                            Title = "Yapılacak 2",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ToDoList.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "abc.123",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
